export const FINDINGS_TEMPLATE = (featureName: string): string => `# Findings: ${featureName}

## Goal
${featureName}

## Instructions

## Discoveries

## Accomplished

## Relevant files / directories

## 下一步

---

*Initialized: Phase 0*

---

## Phase 0: Requirement Clarification

**Status**: ⏳ Pending

### Feature Overview

### Requirement Specifications

### Performance Requirements

### Core Modules

---

*Generated by SDD-Workflow Phase 0*
`